"use client";

import { useBolao } from "./store";
import { ADMINS } from "./mock-data";

/** Retorna o idioma do grupo ativo ("pt" ou "en") */
export function useLang(): "pt" | "en" {
  const { currentGrupoId } = useBolao();
  if (!currentGrupoId) return "pt";
  const cfg = ADMINS.find((a) => a.id === currentGrupoId);
  return cfg?.lang ?? "pt";
}

/** Tradução das strings principais da UI */
export const T = {
  pt: {
    // tabs
    ranking: "Ranking",
    jogos: "Jogos",
    palpites: "Palpites",
    grupos: "Grupos",
    desafios: "Desafios",
    feed: "Feed",
    regras: "Regras",
    // ranking
    rankingGeral: "🏆 Ranking Geral",
    semParticipantes: "Nenhum participante cadastrado ainda.",
    semGrupo: "Sem grupo",
    // jogos / matches
    amistoso: "Amistoso",
    treino: "🎯 TREINO",
    treinoEncerrado: "🎯 TREINO · ENCERRADO",
    treinoNaoContaRanking: "🎯 Treino (não conta no ranking)",
    apostas: "Apostas sempre abertas",
    apostasDesc: "Jogos de treino — apostas sempre abertas, não contam para o ranking.",
    aoVivo: "🔴 AO VIVO",
    encerrado: "ENCERRADO",
    resultadoOficial: "🔒 RESULTADO OFICIAL:",
    // palpites
    previsaoGrupos: "📋 Previsão dos Grupos",
    palpitesJogos: "⚽ Palpites dos Jogos",
    palpitesBloqueados: "🔒 Palpites bloqueados",
    salvePrevisoesPrimeiro: "⚠️ Salve as previsões dos grupos primeiro!",
    preenchaGruposRestantes: (n: number) => `Preencha e salve a previsão dos ${n} grupos restantes primeiro.`,
    irParaPrevisao: "Ir para Previsão dos Grupos",
    disponiveis: "Disponíveis para apostar",
    encerrados: "Palpites encerrados",
    semPalpiteTreino: "Sem palpite neste treino.",
    semPalpiteJogo: "Sem palpite para este jogo → −3 pontos no ranking.",
    seuPalpite: "Seu palpite:",
    voceApostou: "Você apostou:",
    de: "de",
    jogosApostados: "jogos apostados",
    salvarPalpite: "💾 Salvar palpite",
    alterarPalpite: "✏️ Alterar palpite",
    apostar: "🎯 Apostar",
    salvo: "✅ Salvo!",
    palpiteSalvo: "✅ Palpite salvo!",
    resultadoOficialLancado: "🔒 Resultado oficial lançado",
    vitoriaTimes: (side: "A" | "B") => `Vitória time ${side}`,
    empate: "Empate",
    seAcertarExato: "Se acertar o placar exato:",
    seAcertarVencedor: "Se acertar o vencedor:",
    // grupos
    gruposTitle: "📊 Grupos",
    aguardandoInicio: "Aguardando início",
    jogosRealizados: (n: number, t: number) => `${n}/${t} jogos realizados`,
    team: "Time",
    suaPrevisao: "Sua previsão de classificação",
    previsaoNaoTravada: "⚠️ Previsão ainda não travada — vá em Palpites para salvar.",
    emAberto: "⏳ em aberto",
    // breakdown
    breakdownLabels: {
      exact: "Placar exato",
      winner: "Vencedor",
      total: "Total de gols",
      diff: "Diferença de gols",
      golsA: "Gols time A",
      golsB: "Gols time B",
    },
    total: "Total",
  },
  en: {
    // tabs
    ranking: "Ranking",
    jogos: "Matches",
    palpites: "Bets",
    grupos: "Groups",
    desafios: "Challenges",
    feed: "Feed",
    regras: "Rules",
    // ranking
    rankingGeral: "🏆 Overall Ranking",
    semParticipantes: "No participants registered yet.",
    semGrupo: "No group",
    // jogos / matches
    amistoso: "Friendly",
    treino: "🎯 TRAINING",
    treinoEncerrado: "🎯 TRAINING · FINISHED",
    treinoNaoContaRanking: "🎯 Training (does not count for ranking)",
    apostas: "Bets always open",
    apostasDesc: "Training matches — bets always open, do not count for ranking.",
    aoVivo: "🔴 LIVE",
    encerrado: "FINISHED",
    resultadoOficial: "🔒 OFFICIAL RESULT:",
    // palpites
    previsaoGrupos: "📋 Group Stage Predictions",
    palpitesJogos: "⚽ Match Bets",
    palpitesBloqueados: "🔒 Bets locked",
    salvePrevisoesPrimeiro: "⚠️ Save group predictions first!",
    preenchaGruposRestantes: (n: number) => `Fill and save the predictions for the remaining ${n} groups first.`,
    irParaPrevisao: "Go to Group Predictions",
    disponiveis: "Available to bet",
    encerrados: "Closed bets",
    semPalpiteTreino: "No bet placed on this training match.",
    semPalpiteJogo: "No bet for this match → −3 points in ranking.",
    seuPalpite: "Your bet:",
    voceApostou: "You bet:",
    de: "of",
    jogosApostados: "matches bet",
    salvarPalpite: "💾 Save bet",
    alterarPalpite: "✏️ Change bet",
    apostar: "🎯 Bet",
    salvo: "✅ Saved!",
    palpiteSalvo: "✅ Bet saved!",
    resultadoOficialLancado: "🔒 Official result entered",
    vitoriaTimes: (side: "A" | "B") => `Team ${side} wins`,
    empate: "Draw",
    seAcertarExato: "If you nail the exact score:",
    seAcertarVencedor: "If you get the winner:",
    // grupos
    gruposTitle: "📊 Groups",
    aguardandoInicio: "Waiting to start",
    jogosRealizados: (n: number, t: number) => `${n}/${t} matches played`,
    team: "Team",
    suaPrevisao: "Your qualification prediction",
    previsaoNaoTravada: "⚠️ Prediction not locked yet — go to Bets to save.",
    emAberto: "⏳ pending",
    // breakdown
    breakdownLabels: {
      exact: "Exact score",
      winner: "Winner",
      total: "Total goals",
      diff: "Goal difference",
      golsA: "Team A goals",
      golsB: "Team B goals",
    },
    total: "Total",
  },
} as const;

/** Mapa de nomes de países PT → EN */
export const COUNTRY_EN: Record<string, string> = {
  "Brasil": "Brazil",
  "Alemanha": "Germany",
  "Espanha": "Spain",
  "França": "France",
  "Argentina": "Argentina",
  "Portugal": "Portugal",
  "Inglaterra": "England",
  "Holanda": "Netherlands",
  "Bélgica": "Belgium",
  "México": "Mexico",
  "Canadá": "Canada",
  "EUA": "USA",
  "Japão": "Japan",
  "Coreia do Sul": "South Korea",
  "Austrália": "Australia",
  "Marrocos": "Morocco",
  "Senegal": "Senegal",
  "Noruega": "Norway",
  "Suécia": "Sweden",
  "Dinamarca": "Denmark",
  "Irã": "Iran",
  "Arábia Saudita": "Saudi Arabia",
  "Turquia": "Turkey",
  "Croácia": "Croatia",
  "Eslovênia": "Slovenia",
  "Colômbia": "Colombia",
  "Jordânia": "Jordan",
  "Equador": "Ecuador",
  "Paraguai": "Paraguay",
  "Uruguai": "Uruguay",
  "Peru": "Peru",
  "Chile": "Chile",
  "África do Sul": "South Africa",
  "Rep. Tcheca": "Czech Republic",
  "Bósnia-Herz.": "Bosnia-Herz.",
  "Qatar": "Qatar",
  "Suíça": "Switzerland",
  "Haiti": "Haiti",
  "Escócia": "Scotland",
  "Irlanda do Norte": "Northern Ireland",
  "Islândia": "Iceland",
  "Curaçao": "Curaçao",
  "C. do Marfim": "Ivory Coast",
  "Tunísia": "Tunisia",
  "Egito": "Egypt",
  "Nova Zelândia": "New Zealand",
  "Cabo Verde": "Cape Verde",
  "Iraque": "Iraq",
  "Argélia": "Algeria",
  "Áustria": "Austria",
  "Rep. Congo": "Congo DR",
  "Uzbequistão": "Uzbekistan",
  "Gana": "Ghana",
  "Panamá": "Panama",
  "Guatemala": "Guatemala",
};

/** Traduz nome de país se lang=en */
export function countryName(name: string, lang: "pt" | "en"): string {
  if (lang === "pt") return name;
  return COUNTRY_EN[name] ?? name;
}
